import re

# Precise evaluation database for technical mapping
QUESTION_EVALUATION_DB = {
    "rest api": {
        "keywords": ["http", "stateless", "endpoint", "resource", "get", "post", "header"],
        "ideal": "REST (Representational State Transfer) is an architectural style utilizing a stateless, client-server protocol (usually HTTP). It exposes resource endpoints using standard methods (GET, POST, PUT, DELETE) and standardized status codes.",
        "follow_up": "What is the difference between idempotent and non-idempotent HTTP methods in REST?",
        "concepts": ["Statelessness", "HTTP verbs", "Resource endpoints"]
    },
    "tell me about yourself": {
        "keywords": ["experience", "project", "background", "developer", "engineer", "passion"],
        "ideal": "A great response outlines your background, highlights 1-2 key technical accomplishments, shows passion for technology, and explains why you are interested in this specific role.",
        "follow_up": "Can you describe the technical architecture of the project you are most proud of?",
        "concepts": ["Professional summary", "Key technical project", "Role alignment"]
    },
    "database index": {
        "keywords": ["b-tree", "search", "query", "speed", "performance", "read", "write"],
        "ideal": "A database index is a data structure (typically a B-Tree) that improves the speed of data retrieval operations on a table at the cost of additional writes and storage. It allows queries to locate records without performing a full table scan.",
        "follow_up": "How does indexing affect write operations like INSERT, UPDATE, and DELETE?",
        "concepts": ["B-Tree structure", "Query execution speed", "Write overhead"]
    },
    "sql vs nosql": {
        "keywords": ["relational", "schema", "scaling", "document", "key-value", "acid", "join"],
        "ideal": "SQL databases are relational, schema-based, table-structured, and support ACID transactions. NoSQL databases are non-relational, schema-less, document or key-value structured, horizontally scalable, and often compromise transactional rigidity for speed.",
        "follow_up": "Can you explain CAP theorem and how it relates to SQL vs NoSQL scaling?",
        "concepts": ["Relational schemas", "Horizontal scalability", "ACID transactions"]
    },
    "react hooks": {
        "keywords": ["state", "functional", "effect", "ref", "rules", "re-render", "lifecycle"],
        "ideal": "React Hooks are functions that let functional components manage state and side-effects (e.g. useState, useEffect). Key rules include calling them only at the top level and only from React function components or custom hooks.",
        "follow_up": "What is the dependency array in useEffect and what happens if you omit it?",
        "concepts": ["State management in functions", "Rules of hooks", "Lifecycle/effect syncing"]
    },
    "process and a thread": {
        "keywords": ["memory", "cpu", "execution", "shared", "isolation", "overhead", "ipc"],
        "ideal": "A process is an independent execution unit with its own allocated memory space. A thread is a subset execution unit within a process that shares memory and resources with other threads in that same process.",
        "follow_up": "How do you handle thread safety and synchronize shared data in a multi-threaded system?",
        "concepts": ["Resource allocation isolation", "Shared memory execution", "Synchronization overhead"]
    },
    "vector database": {
        "keywords": ["embedding", "semantic", "similarity", "distance", "knn", "search", "rag"],
        "ideal": "A vector database indexes and stores high-dimensional vector embeddings generated by machine learning models. It supports fast nearest-neighbor (k-NN) queries to perform semantic similarity search.",
        "follow_up": "What similarity metrics are commonly used in vector search (e.g. Cosine Similarity vs L2 Distance)?",
        "concepts": ["Vector embeddings", "Similarity distance metrics", "Semantic search retrieval"]
    },
    "game loop": {
        "keywords": ["update", "render", "input", "physics", "frame", "fps", "time"],
        "ideal": "The game loop is the central run cycle in game development. It continuously processes user input, updates game and physics state, and renders the frame to the screen, running repeatedly until the game exits.",
        "follow_up": "Why is it important to use delta time when calculating player movement inside the update loop?",
        "concepts": ["State updates", "Frame rendering", "Time delta synchronization"]
    },
    "state vs props": {
        "keywords": ["immutable", "mutable", "parent", "component", "re-render", "update"],
        "ideal": "In React, state represents mutable data managed internally by the component itself, whereas props are immutable parameters passed down by a parent component.",
        "follow_up": "What are some patterns for lifting state up, and how does context API help with prop drilling?",
        "concepts": ["Internal component state", "Immutable parent parameters", "Unidirectional data flow"]
    },
    "gil": {
        "keywords": ["global", "lock", "thread", "concurrency", "multiprocessing", "cpu-bound"],
        "ideal": "The Global Interpreter Lock (GIL) is a mutex in CPython that ensures only one thread executes Python bytecode at a time. This simplifies memory management but limits performance for multi-threaded CPU-bound programs.",
        "follow_up": "How can you run tasks in parallel in Python to bypass the GIL constraint?",
        "concepts": ["CPython bytecode execution lock", "CPU-bound concurrency limits", "Multiprocessing workarounds"]
    },
    "cap theorem": {
        "keywords": ["consistency", "availability", "partition", "tolerance", "network", "distributed"],
        "ideal": "The CAP theorem states that a distributed data store can simultaneously provide at most two of three guarantees: Consistency (every read receives the most recent write), Availability (every request receives a non-error response), and Partition Tolerance (the system continues to operate despite network failures).",
        "follow_up": "Which guarantees does a typical relational database (like PostgreSQL) prioritize over a NoSQL database (like Cassandra) under network partition?",
        "concepts": ["Distributed system trade-offs", "Network partition resilience", "Consistency vs Availability"]
    },
    "self-attention": {
        "keywords": ["transformer", "weight", "token", "query", "key", "value", "context"],
        "ideal": "Self-attention is a mechanism in Transformers that allows tokens in a sequence to calculate attention weights relative to all other tokens. It uses Query, Key, and Value vectors to capture contextual relationships regardless of distance.",
        "follow_up": "How does scaled dot-product attention compute weights mathematically?",
        "concepts": ["Token context relationships", "Query-Key-Value projection", "Transformers architecture"]
    }
}

def detect_category(question: str) -> str:
    """
    Heuristically classifies the question text into one of 5 categories:
    HR, Technical, Coding, System Design, or Project Discussion.
    """
    q_lower = question.lower()
    
    # 1. Project Discussion checks
    if any(phrase in q_lower for phrase in ["proud of", "your project", "previous project", "describe a project", "tell me about a project", "project you built"]):
        return "Project Discussion"
        
    # 2. HR / Behavioral checks
    if any(phrase in q_lower for phrase in ["tell me about yourself", "why do you want", "disagree", "deadline", "conflict", "weakness", "strength", "leadership", "teamwork", "handle a situation", "describe a time", "how do you handle"]):
        return "HR"
        
    # 3. Coding checks
    if any(phrase in q_lower for phrase in ["write a", "implement a", "implement an algorithm", "solve the", "coding challenge", "program to", "function to", "sql query", "decorator", "palindrome", "fibonacci"]):
        return "Coding"
        
    # 4. System Design checks
    if any(phrase in q_lower for phrase in ["design a", "design the", "system design", "load balancer", "scaling", "architecture for", "cdn", "kafka", "twilio", "cap theorem", "slack", "twitter"]):
        return "System Design"
        
    # 5. Default to Technical
    return "Technical"

def evaluate_hr(question: str, answer: str) -> dict:
    """
    HR Rubric: Communication, STAR structure, Confidence, Leadership, Teamwork
    """
    ans_lower = answer.lower()
    strengths = []
    weaknesses = []
    missing_concepts = []
    
    # 1. Communication (transition words check)
    struct_words = ["because", "therefore", "first", "second", "however", "consequently"]
    comm_score = min(2, sum(1 for w in struct_words if w in ans_lower))
    if comm_score >= 2:
        strengths.append("Structured communication style with smooth transitions.")
    else:
        weaknesses.append("Try organizing your points with transitions (e.g. 'firstly', 'secondly').")
        
    # 2. STAR Structure
    star_words = ["situation", "task", "action", "result", "consequently", "resolved", "solved"]
    has_star = sum(1 for w in star_words if w in ans_lower)
    star_score = 2 if has_star >= 2 else 1 if has_star >= 1 else 0
    if star_score == 2:
        strengths.append("Followed the STAR (Situation, Task, Action, Result) method framework.")
    else:
        weaknesses.append("Ensure your story explicitly defines the Situation, Task, Action, and Result (STAR method).")
        missing_concepts.append("STAR storytelling structure")
        
    # 3. Confidence (absence of hesitant words)
    hesitant_words = ["maybe", "guess", "probably", "i think", "sort of", "kind of"]
    has_hesitant = any(w in ans_lower for w in hesitant_words)
    confidence_score = 1 if has_hesitant else 2
    if confidence_score == 2:
        strengths.append("Assertive tone with confident word choices.")
    else:
        weaknesses.append("Avoid hesitant phrases like 'I think' or 'maybe' to project more authority.")
        
    # 4. Leadership
    lead_words = ["led", "guided", "spearheaded", "directed", "mentored", "initiated", "responsible"]
    has_lead = any(w in ans_lower for w in lead_words)
    lead_score = 2 if has_lead else 0
    if lead_score == 2:
        strengths.append("Highlighted proactive leadership and ownership.")
    else:
        weaknesses.append("Incorporate examples of taking direct initiative or leading a task.")
        missing_concepts.append("Leadership & Initiative indicators")
        
    # 5. Teamwork
    team_words = ["team", "collaborated", "together", "we", "shared", "partnered", "supported"]
    has_team = any(w in ans_lower for w in team_words)
    team_score = 2 if has_team else 0
    if team_score == 2:
        strengths.append("Communicated strong collaboration and teamwork alignment.")
    else:
        weaknesses.append("Balance your achievements by mentioning team syncs and support.")
        missing_concepts.append("Team collaboration keywords")
        
    score = comm_score + star_score + confidence_score + lead_score + team_score
    score = min(10, max(1, score))
    
    ideal = "An ideal behavioral response starts with the Situation (10%), defines the Task and constraints (15%), details your specific Action (60%), and finishes with a quantifiable positive Result (15%)."
    follow_up = "What was the direct impact of your actions on the team's timeline or final deliverable?"
    
    return {
        "score": score,
        "strengths": strengths,
        "weaknesses": weaknesses,
        "missingConcepts": missing_concepts,
        "idealAnswer": ideal,
        "followUpQuestion": follow_up
    }

def evaluate_technical(question: str, answer: str, role: str) -> dict:
    """
    Technical Rubric: Accuracy, Technical depth, Terminology, Practical understanding
    """
    ans_lower = answer.lower(); q_lower = question.lower()
    strengths = []
    weaknesses = []
    missing_concepts = []
    
    # Identify Closest Question in Database
    match_info = None
    for key, info in QUESTION_EVALUATION_DB.items():
        if key in q_lower:
            match_info = info
            break
            
    # 1. Technical Depth (length score)
    words = [w for w in answer.split() if w]
    depth_score = min(3, len(words) // 15) # up to 3 points
    if depth_score >= 2:
        strengths.append("Response shows good technical depth and explanation length.")
    else:
        weaknesses.append("Elaborate further on internal mechanics; response is too brief.")
        
    # 2 & 3. Accuracy and Terminology (up to 5 points)
    accuracy_score = 0
    if match_info:
        target_kws = match_info["keywords"]
        matched_kws = [kw for kw in target_kws if re.search(rf"\b{re.escape(kw)}\b", ans_lower)]
        unmatched_kws = [kw for kw in target_kws if kw not in matched_kws]
        
        ratio = len(matched_kws) / len(target_kws)
        accuracy_score = int(ratio * 5)
        
        if len(matched_kws) > 0:
            strengths.append(f"Accurate usage of primary terms: {', '.join(matched_kws[:3])}.")
        if len(unmatched_kws) > 0:
            weaknesses.append(f"Incorporate missing core terms like: {', '.join(unmatched_kws[:2])}.")
            
        concepts = match_info["concepts"]
        for idx, concept in enumerate(concepts):
            kw_index = min(idx, len(target_kws) - 1)
            if target_kws[kw_index] not in matched_kws:
                missing_concepts.append(concept)
                
        ideal = match_info["ideal"]
        follow_up = match_info["follow_up"]
    else:
        # Fallback role-based keywords check
        fallback_map = {
            "game developer": ["unity", "unreal", "c#", "c++", "physics", "rendering", "oop"],
            "frontend developer": ["react", "javascript", "html", "css", "state", "dom"],
            "backend developer": ["python", "api", "database", "sql", "server", "docker"],
            "ai/ml engineer": ["python", "model", "learning", "tensorflow", "pytorch", "data"],
            "software engineer": ["code", "design", "oop", "algorithm", "git", "data"]
        }
        kws = fallback_map.get(role.lower(), ["architecture", "systems", "implementation"])
        matched_kws = [kw for kw in kws if kw in ans_lower]
        accuracy_score = min(5, len(matched_kws) * 1)
        
        if len(matched_kws) > 0:
            strengths.append(f"Mentioned core role domain terms: {', '.join(matched_kws[:2])}.")
        else:
            weaknesses.append("Align terminology with core software engineering concepts.")
            missing_concepts.append("Domain-specific architectural keywords")
            
        ideal = "Define the core technical mechanism, describe how it interacts with other modules, and outline its performance trade-offs."
        follow_up = "How does this scale or bottleneck under high load conditions?"
        
    # 4. Practical Understanding (check for examples / projects)
    practical_words = ["example", "project", "production", "use case", "experience", "applied", "work"]
    has_practical = any(w in ans_lower for w in practical_words)
    practical_score = 2 if has_practical else 0
    if practical_score == 2:
        strengths.append("Linked theoretical concept with practical application/projects.")
    else:
        weaknesses.append("Provide a short real-world scenario where you utilized this concept.")
        missing_concepts.append("Production application context")
        
    score = depth_score + accuracy_score + practical_score
    score = min(10, max(1, score))
    
    return {
        "score": score,
        "strengths": strengths,
        "weaknesses": weaknesses,
        "missingConcepts": missing_concepts,
        "idealAnswer": ideal,
        "followUpQuestion": follow_up
    }

def evaluate_coding(question: str, answer: str) -> dict:
    """
    Coding Rubric: Algorithm, Complexity, Edge cases, Code quality
    """
    ans_lower = answer.lower()
    strengths = []
    weaknesses = []
    missing_concepts = []
    
    # 1. Algorithm implementation structure
    algo_words = ["loop", "recursion", "array", "pointer", "time", "space", "tree", "hash", "list", "stack", "queue"]
    has_algo = sum(1 for w in algo_words if w in ans_lower)
    algo_score = min(3, has_algo // 2 + 1)
    if algo_score >= 2:
        strengths.append("Understands the core data structure or algorithmic pattern.")
    else:
        weaknesses.append("Focus on details of the exact sorting, traversing, or mapping algorithm.")
        
    # 2. Complexity Analysis
    complexity_patterns = [r"\bo\(", r"complexity", r"time complexity", r"space complexity", r"big o", r"runtime"]
    has_complexity = any(re.search(pat, ans_lower) for pat in complexity_patterns)
    complexity_score = 2 if has_complexity else 0
    if complexity_score == 2:
        strengths.append("Explicitly discussed space/time complexity bounds.")
    else:
        weaknesses.append("Missing Big O notation; state the space and time complexity explicitly.")
        missing_concepts.append("Big O Complexity Analysis")
        
    # 3. Edge Cases
    edge_words = ["edge", "null", "empty", "boundary", "zero", "negative", "overflow", "exception", "error", "bounds"]
    has_edge = any(w in ans_lower for w in edge_words)
    edge_score = 2 if has_edge else 0
    if edge_score == 2:
        strengths.append("Considered boundaries, errors, and input edge cases.")
    else:
        weaknesses.append("Explain how your code behaves with empty, null, or extreme boundary inputs.")
        missing_concepts.append("Input Validation & Edge Case Check")
        
    # 4. Code Quality / Syntax structure
    syntax_words = ["def ", "return", "class", "function", "let ", "const ", "if ", "while", "for ", "{", "}", "import"]
    has_syntax = sum(1 for w in syntax_words if w in ans_lower)
    syntax_score = min(3, has_syntax)
    if syntax_score >= 2:
        strengths.append("Structured answers with valid code syntax or clear pseudo-code blocks.")
    else:
        weaknesses.append("Use proper indentation and code structures rather than raw paragraphs.")
        missing_concepts.append("Structured Code Syntax / Pseudo-code")
        
    score = algo_score + complexity_score + edge_score + syntax_score
    score = min(10, max(1, score))
    
    ideal = "Write a clean function definition, validate inputs for edge cases (null/empty), implement the algorithm using efficient data structures, write comments, and state the exact time complexity (e.g. O(N)) and space complexity (e.g. O(1))."
    follow_up = "What is the worst-case space complexity of your solution and can it be optimized?"
    
    return {
        "score": score,
        "strengths": strengths,
        "weaknesses": weaknesses,
        "missingConcepts": missing_concepts,
        "idealAnswer": ideal,
        "followUpQuestion": follow_up
    }

def evaluate_system_design(question: str, answer: str) -> dict:
    """
    System Design Rubric: Scalability, Trade-offs, Components, API design/Data flow
    """
    ans_lower = answer.lower()
    strengths = []
    weaknesses = []
    missing_concepts = []
    
    # 1. Scalability
    scale_words = ["scale", "scaling", "load balancer", "cache", "partition", "sharding", "replication", "availability"]
    has_scale = any(w in ans_lower for w in scale_words)
    scale_score = 3 if has_scale else 0
    if scale_score == 3:
        strengths.append("Incorporated horizontal scaling, database sharding, or load balancing.")
    else:
        weaknesses.append("Elaborate on how to scale out the system to handle millions of requests.")
        missing_concepts.append("Horizontal scaling & Replication")
        
    # 2. Trade-offs
    trade_words = ["trade-off", "latency", "throughput", "cap theorem", "consistency", "availability", "alternative"]
    has_trade = any(w in ans_lower for w in trade_words)
    trade_score = 2 if has_trade else 0
    if trade_score == 2:
        strengths.append("Demonstrated trade-off evaluation (e.g. latency vs consistency).")
    else:
        weaknesses.append("Discuss the trade-offs of your storage and caching choices (e.g. CAP theorem constraints).")
        missing_concepts.append("Architectural Trade-offs (CAP)")
        
    # 3. System Components
    component_words = ["database", "queue", "cdn", "microservice", "gateway", "redis", "nginx", "cache", "broker"]
    has_component = sum(1 for w in component_words if w in ans_lower)
    component_score = min(3, has_component // 2 + 1)
    if component_score >= 2:
        strengths.append("Clearly mapped key system blocks (load balancers, CDN, Redis cache, database).")
    else:
        weaknesses.append("Break down your architecture into dedicated blocks (e.g., caching, message broker).")
        missing_concepts.append("Component isolation & Message queuing")
        
    # 4. API Design & Data Flow
    api_words = ["api", "request", "response", "payload", "json", "grpc", "rest", "event", "message"]
    has_api = any(w in ans_lower for w in api_words)
    api_score = 2 if has_api else 0
    if api_score == 2:
        strengths.append("Outlined data flows or API endpoint schemas.")
    else:
        weaknesses.append("Explain the API schema or the data exchange protocol between microservices.")
        missing_concepts.append("API Gateway / Contract design")
        
    score = scale_score + trade_score + component_score + api_score
    score = min(10, max(1, score))
    
    ideal = "Outline the scope and constraints (DAU, storage size), draw high-level components (client, LB, server, database, cache, message broker), design the API contract, and conclude by identifying bottlenecks (single points of failure, scaling databases)."
    follow_up = "How would you handle database replication and failovers if the primary node goes offline?"
    
    return {
        "score": score,
        "strengths": strengths,
        "weaknesses": weaknesses,
        "missingConcepts": missing_concepts,
        "idealAnswer": ideal,
        "followUpQuestion": follow_up
    }

def evaluate_project_discussion(question: str, answer: str) -> dict:
    """
    Project Discussion Rubric: Architecture, Technologies, Challenges, Outcomes
    """
    ans_lower = answer.lower()
    strengths = []
    weaknesses = []
    missing_concepts = []
    
    # 1. Architecture
    arch_words = ["design", "architecture", "structure", "microservice", "mvc", "monolith", "layers"]
    has_arch = any(w in ans_lower for w in arch_words)
    arch_score = 2 if has_arch else 0
    if arch_score == 2:
        strengths.append("Described the high-level architecture of your project.")
    else:
        weaknesses.append("Define the architectural layout (e.g. client-server, microservices) of your project.")
        missing_concepts.append("System Architecture description")
        
    # 2. Technologies
    tech_words = ["react", "next.js", "django", "flask", "fastapi", "postgres", "mysql", "mongodb", "docker", "python", "javascript", "typescript", "c++", "c#", "unity"]
    has_tech = sum(1 for w in tech_words if w in ans_lower)
    tech_score = min(3, has_tech)
    if tech_score >= 2:
        strengths.append("Explicitly named your technical stack choices.")
    else:
        weaknesses.append("List the specific frameworks, databases, and languages used in the project.")
        missing_concepts.append("Stack selection rationale")
        
    # 3. Challenges
    challenge_words = ["challenge", "difficulty", "bug", "problem", "solve", "bottleneck", "issue", "deadlock"]
    has_challenge = any(w in ans_lower for w in challenge_words)
    challenge_score = 3 if has_challenge else 0
    if challenge_score == 3:
        strengths.append("Detailed a complex challenge or bug you successfully resolved.")
    else:
        weaknesses.append("Highlight a specific technical blocker or performance bottleneck you resolved.")
        missing_concepts.append("Problem-solving & Blocker resolution")
        
    # 4. Outcomes / Metrics
    outcome_words = ["result", "outcome", "percent", "%", "faster", "reduced", "improve", "delivered", "metric"]
    has_outcome = any(w in ans_lower for w in outcome_words)
    outcome_score = 2 if has_outcome else 0
    if outcome_score == 2:
        strengths.append("Quantified project achievements or business impact outcomes.")
    else:
        weaknesses.append("Quantify the outcome (e.g. 'reduced latency by 20%', 'increased test coverage').")
        missing_concepts.append("Metric-based impact results")
        
    score = arch_score + tech_score + challenge_score + outcome_score
    score = min(10, max(1, score))
    
    ideal = "State the project purpose, specify the architecture and stack (technologies), explain a major technical roadblock (challenge), explain how you diagnosed and resolved it, and detail the metrics-based outcomes."
    follow_up = "Why did you choose this technical stack over alternatives, and what was your individual contribution?"
    
    return {
        "score": score,
        "strengths": strengths,
        "weaknesses": weaknesses,
        "missingConcepts": missing_concepts,
        "idealAnswer": ideal,
        "followUpQuestion": follow_up
    }

def evaluate_interview_answer(question: str, answer: str, role: str) -> dict:
    """
    Classifies the interview question, runs category-specific scoring evaluation,
    and returns a cohesive feedback payload.
    """
    category = detect_category(question)
    
    # 1. Base check for blank/brief answers
    words = [w for w in answer.strip().split() if w]
    if len(words) < 5:
        return {
            "score": 1,
            "strengths": ["Recognized the request and initiated a reply."],
            "weaknesses": ["Answer is too brief to evaluate.", "Fails to provide sufficient technical depth."],
            "missingConcepts": ["Fundamental definitions", "Technical terminology"],
            "idealAnswer": "Provide a complete definition, trace implementation steps, and mention projects or metrics.",
            "followUpQuestion": "Could you try explaining this topic with a concrete example?",
            "confidenceLevel": "Low"
        }
        
    # 2. Route evaluation to category-specific scoring
    if category == "HR":
        eval_result = evaluate_hr(question, answer)
    elif category == "Coding":
        eval_result = evaluate_coding(question, answer)
    elif category == "System Design":
        eval_result = evaluate_system_design(question, answer)
    elif category == "Project Discussion":
        eval_result = evaluate_project_discussion(question, answer)
    else:
        eval_result = evaluate_technical(question, answer, role)
        
    # 3. Add Confidence Level based on score
    score = eval_result["score"]
    if score >= 8:
        confidence = "High"
    elif score >= 5:
        confidence = "Medium"
    else:
        confidence = "Low"
        
    eval_result["confidenceLevel"] = confidence
    
    return eval_result
